// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accept': string;
  'reject': string;
  'review': string;
}
export const cssExports: CssExports;
export default cssExports;
