// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'invalid': string;
  'valid': string;
}
export const cssExports: CssExports;
export default cssExports;
