// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'container': string;
  'icon': string;
  'textArea': string;
}
export const cssExports: CssExports;
export default cssExports;
