// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'button': string;
  'content': string;
  'div': string;
  'label': string;
  'open': string;
}
export const cssExports: CssExports;
export default cssExports;
