// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'active': string;
  'content': string;
  'list': string;
}
export const cssExports: CssExports;
export default cssExports;
