// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cancelButton': string;
  'info': string;
  'label': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
