// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'approve': string;
  'button': string;
  'danger': string;
}
export const cssExports: CssExports;
export default cssExports;
