// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'field': string;
  'header': string;
  'register': string;
  'submit': string;
  'textbox': string;
}
export const cssExports: CssExports;
export default cssExports;
