// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'canClose': string;
  'canOpen': string;
}
export const cssExports: CssExports;
export default cssExports;
